# Generated by Django 6.0.4 on 2026-04-13 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_cointransaction_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='price_coins',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
